snmp:
  community: public
  port: 161
  trap_destination: 192.168.1.100
  trap_port: 162

gpio:
  alarm_pin: 17
  supervision_pin: 27
  trouble_pin: 22
  debounce_time: 5

oids:
  alarm: 1.3.6.1.4.1.99999.1.1.1
  supervision: 1.3.6.1.4.1.99999.1.1.2
  trouble: 1.3.6.1.4.1.99999.1.1.3
  event: 1.3.6.1.4.1.99999.1.1.4

serial:
  port: '/dev/serial-adapter'
  baudrate: 9600
  bytesize: 8
  parity: 'none'
  stopbits: 1
  timeout: 1